trigger:
- none

jobs:

  - job: PublishPipelineArtifact
    dependsOn:
      - FunctionsV1Tests
      - FunctionsV2Tests

    pool: 
      vmImage: 'windows-latest'

    variables:
      solution: 'WebJobs.Extensions.DurableTask.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@0

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/**/*.csproj'
        feedsToUse: 'config'
        nugetConfigPath: '.nuget/nuget.config'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: EsrpCodeSigning@1
    displayName: 'ESRP CodeSigning: Authenticode'
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: '**/$(BuildConfiguration)\Release'
      Pattern: '*DurableTask.dll'
      SessionTimeout: '60'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'
      signConfigType: inlineSignParams
      inlineOperation: |
      [    
         :{
           "KeyCode": "CP-230012",
           "OperationCode": "SigntoolSign",
           "Parameters": {
             "OpusName": "Microsoft",
             "OpusInfo": "http://www.microsoft.com",
             "FileDigest": "/fd \"SHA256\"",
             "PageHash": "/NPH",
             "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
           },
           "ToolName": "sign",
           "ToolVersion": "1.0"
         },
         {
           "KeyCode": "CP-230012",
           "OperationCode": "SigntoolVerify",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         }
      ]

    - task: EsrpCodeSigning@1
    displayName: 'ESRP CodeSigning: Nupkg'
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: '**/$(BuildConfiguration)\Release'
      Pattern: '*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
      [
         {
           "KeyCode": "CP-401405",
           "OperationCode": "NuGetSign",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         },
         {
           "KeyCode": "CP-401405",
           "OperationCode": "NuGetVerify",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         }
      ]
      condition: and(succeeded(), startsWith(variables['SignArtifacts'], 'true'))

    - publish: 'src/WebJobs.Extensions.DurableTask/bin'
      artifact: bin